from selenium import webdriver
from time import sleep
# d = webdriver.Chrome()
# d.get('https://mail.qq.com/')
# sleep(2)
# d.find_element_by_id('switcher_plogin').click()
# sleep(4)
# em = d.find_element_by_id('u')
# em.clear()
# em.send_keys('616736353@qq.com')
# ps = d.find_element_by_id('p')
# ps.clear()
# ps.send_keys('145692love!!')
# l = d.find_element_by_id('p_low_login_enable')
# sleep(3)
# l.click()
# dl = d.find_element_by_id('login_button')
# sleep(3)
# dl.click()
d = webdriver.Firefox()
d.get('http://mail.163.com/')
sleep(3)

d.find_element_by_xpath('//*[@id="lbNormal"]').click()
sleep(3)
d.switch_to.frame('x-URS-iframe')
sleep(3)
em = d.find_element_by_xpath("//*[@id='login-form']/div/div[1]/div[2]/input")
em.send_keys('616736353')
ps = d.find_element_by_name('password')
ps.send_keys('52678love')
d.find_element_by_id('dologin').click()
sleep(5)
d.quit()